# Generated by Django 4.2.3 on 2024-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=12, null=True)),
                ("phone", models.CharField(max_length=12)),
                ("code", models.SmallIntegerField(blank=True, null=True)),
                ("expiration_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "کد:otp",
                "verbose_name_plural": "کد:otp ها",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name=" ایمیل",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name=" نام کاربری",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name=" نام و نام خانوادگی",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name=" شماره تلفن"
                    ),
                ),
                (
                    "password_copy",
                    models.TextField(
                        blank=True, null=True, verbose_name=" کپی از پسورد کاربر"
                    ),
                ),
                (
                    "is_shopkeeper",
                    models.BooleanField(
                        default=False, null=True, verbose_name="مغازه دار"
                    ),
                ),
                (
                    "is_simple_user",
                    models.BooleanField(
                        default=False, null=True, verbose_name=" کاربر ساده"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name=" فعال")),
                ("is_admin", models.BooleanField(default=False, verbose_name=" ادمین")),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربرها",
                "ordering": ("-date_added",),
            },
        ),
    ]
