# Generated by Django 4.2.3 on 2024-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_delete_otp_remove_user_password_copy_user_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_copy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
